### ISSUE TITLE
This directive works not correct in the iteration

### ISSUE THREAD

**Issue by vukhanhtruong** [mattlewis92/angular2-bootstrap-confirm#15] opened 2016-06-28 07:09 UTC
Hi,

Since I update from 0.4.2 to 0.6.0, I put your directive into the template iteration (ngFor), and it works not correctly.

Please check this issue.
Thanks & Regards,

**Comment by mattlewis92** [comment] 2016-06-28 07:24
The demo runs [in a ngFor](https://github.com/mattlewis92/angular2-bootstrap-confirm/blob/master/demo/demo.ts#L42) with no issues, can you share some example code that reproduces your issue, thanks! 😄

**Comment by vukhanhtruong** [comment] 2016-06-28 07:31
I catched the issue. If your button has the attribute [(isOpen)]="isOpen" , it will raise the problem.

**Comment by mattlewis92** [comment] 2016-06-28 07:48
That already got fixed in 0.5.2: https://github.com/mattlewis92/angular2-bootstrap-confirm/commit/fe5516d, are you definitely on version 0.6.0? Are you also on the latest angular RC3?

**Comment by vukhanhtruong** [comment] 2016-06-28 07:49
yes, angular RC3.

**Comment by mattlewis92** [comment] 2016-06-28 07:51
and 0.6.0 of this module? Adding ` [(isOpen)]="isOpen"` to the demo works fine for me

**Comment by vukhanhtruong** [comment] 2016-06-28 08:06
The following image is what I get when I add the `isOpen` attribute to my app.

https://s32.postimg.org/rcoe6r7np/screenshot_localhost_5000_2016_06_28_15_06_27.png

**Comment by mattlewis92** [comment] 2016-06-28 08:12
That's really odd, I have no idea why it would be doing that. Unless you can share some example code that reproduces your problem that I can debug I can't help you...

**Comment by vukhanhtruong** [comment] 2016-06-28 08:19
Here's my code:
- Component: http://pastebin.com/PsMcEv4z
- Template:  http://pastebin.com/Bv4f2UXi
That's it.

**Comment by mattlewis92** [comment] 2016-06-28 08:36
Ah I see what's happening now, it's because `isOpen` is bound to every instance of the directive. i.e. when you open 1, `isOpen` becomes true and opens every other popover. I'd recommend just removing it if you don't need to know when a popover is opened or bind it to `item.isOpen` so it'll be a unique variable to just that row 😄

**Closed by mattlewis92** 2016-06-28 08:36 UTC

**Comment by vukhanhtruong** [comment] 2016-06-28 08:39
Is there any way to know that the confirm box is opening or not?

**Comment by mattlewis92** [comment] 2016-06-28 08:42
Bind to a unique variable for each row like so: `isOpen="[(item.isOpen)]"`?

**Comment by mattlewis92** [comment] 2016-06-28 08:43
You can also bind to the de-sugared event `(isOpenChange)="$event"` where $event contains a boolean if the popover is opened on not

**Comment by vukhanhtruong** [comment] 2016-06-28 08:47
It works like charm. Thanks so much for your sharing & supporting. Keep your work up.

**Comment by mattlewis92** [comment] 2016-06-28 08:48
Glad you got it sorted! 👍
